apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: vprofile
spec:
  type: NodePort
  selector:
    app: vproapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb-service
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache-service
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: vprocache
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
    name: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: vpromq-service
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: vpromq
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
